apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The infra department
spec:
  type: department
  # Intentional no profile for testing
  parent: acme-corp
  children: [backstage, boxoffice]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: manjunathmkotabal
spec:
  profile:
    # Intentional no displayName for testing
    email: manjunathmkotabal99@gmail.com
    picture: https://avatars.githubusercontent.com/u/94886901?v=4
  memberOf: [infrastructure]